site_name: My Docs
theme:
  name: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            separate_signature: true
